#테스트용
version: '1'
services:
  mysql_test:
    image: mysql:8.0
    container_name: mysql_container_test
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    #    volumes:
    #      - mysql_data:/var/lib/mysql
    networks:
      - spring-network-test

  phpmyadmin_test:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_test
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "8083:80"
    networks:
      - spring-network-test

volumes:
  mysql_data:

networks:
  spring-network-test:
